spring:
  profiles:
    active: ${APP_PROFILE:test}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

default:
  sender: ${EMAIL_SENDER:vazio}
  recipient: ${EMAIL_RECIPIENT:vazio}

jwt:
  secret: ${JWT_SECRET:vazios}
  expiration: ${JWT_EXPIRATION:86400}