spring:
  jpa:
    properties:
#      javax:
#        persistence:
#          schema-generation:
#            scripts:
#              create-target: create.sql
#              action: create
#            create-source: metadata
      hibernate:
#        hbm2ddl:
#          delimiter: ;
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: create
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/cursomc
    password: 'develop'
  mail:
    properties:
      mail:
        smtp:
          socketFactory:
            port: '465'
            class: javax.net.ssl.SSLSocketFactory
            fallback: 'false'
          starttls:
            enable: 'true'
          ssl:
            enable: 'true'
          auth: 'true'
    host: smtp.mail.yahoo.com
    username: ${EMAIL_USERNAME:vazio}
    password: ${EMAIL_PASSWORD:vazio}
