spring:
  profiles:
    active: ${APP_PROFILE:test}

default:
  sender: ${EMAIL_SENDER:vazio}
  recipient: ${EMAIL_RECIPIENT:vazio}

jwt:
  secret: ${JWT_SECRET:vazios}
  expiration: ${JWT_EXPIRATION:86400000}

s3:
  region: sa-east-1
  bucket: curso-spring-ionic-nilson
aws:
  access_key_id: ${AWS_KEY:vazio}
  secret_access_key: ${AWS_SECRET:vazio}