spring:
  jpa:
    properties:
#      javax:
#        persistence:
#          schema-generation:
#            scripts:
#              create-target: create.sql
#              action: create
#            create-source: metadata
      hibernate:
#        hbm2ddl:
#          delimiter: ;
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: create-drop
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/cursomc
    password: 'develop'
