spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/curso_spring
    password: ''
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: create
    show-sql: 'true'