spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/cursomc
    password: 'develop'
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: create
    show-sql: 'true'