spring:
  datasource:
    url: ${DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: none
  mail:
    properties:
      mail:
        smtp:
          socketFactory:
            port: '465'
            class: javax.net.ssl.SSLSocketFactory
            fallback: 'false'
          starttls:
            enable: 'true'
          ssl:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: ${EMAIL_USERNAME:vazio}
    password: ${EMAIL_PASSWORD:vazio}
